### PR TITLE
Attempt to upgrade JavaParser (many tests are failing)

### PR DESCRIPTION
**Pull request by kelloggm**
@LoiNguyenCS can you look into why? Unfortunately I'm out of time today and I probably won't get another chance to look at this for a day or two.

This upgrade is motivated by the fact that we've been using a version of JavaParser from 2021, and I think that the bug in #116 (see my comment there) may have been fixed in a recent JavaParser version. We should be on the latest JavaParser version regardless, since the library is under active development.

### CODE REVIEW

**Comment by LoiNguyenCS** [comment]
Professor,

The reason why the test is failing seems to be that this new version of JavaParser no longer removes comments in the final output as expected. I will create another PR to fix this issue.

**Comment by LoiNguyenCS** [comment]
The PR continues to fail due to the updated JavaParser's behavior, which no longer requires strict resolution of a class to calculate the resolved type of an instance. For example, even if there is no constructor for `Foo` within the `Foo` class, the new JavaParser version can still calculate the resolved type of `new Foo("Starting")`. Consequently, the `canBeSolved` method within `UnsolvedSymbolVisitor` is not precise anymore.

**Comment by kelloggm** [comment]
> no longer requires strict resolution of a class to calculate the resolved type of an instance

Hmm, this is interesting. How difficult do you think it will be to refactor our code to adapt to JavaParser's change here?

**Comment by LoiNguyenCS** [comment]
> How difficult do you think it will be to refactor our code to adapt to JavaParser's change here?

Updating the `UnsolvedSymbolVisitor` could be difficult, because it was developed based on the limitation of the older version of JavaParser, which is the requirement of strict resolution of a class to determine the type of a method or field. Over time, we've found this limitation to be a feature rather than a bug (we use it to check if our synthetic classes are completely resolved). Therefore, I suggest postponing the update until later, perhaps after we've submitted the paper.

**Comment by kelloggm** [comment]
Superseded by #266.

**Pull request closed without merging**
